### PR TITLE
feat(TPG >=5.24)!: Allow modifying of node type in redis cluster sub-module

### LINKED ISSUE #205: Add node_type in redis cluster module
### TL;DR

Add node_type as input for redis cluster
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_cluster#node_type

### Terraform Resources

```markdown
google_redis_cluster

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_cluster#node_type
```

### Detailed design

```markdown
n/a
```

### Additional information

n/a

### PR DESCRIPTION
**Pull request by ivankennethwang**
fix #205

### CODE REVIEW

**Comment by ivankennethwang** [comment]
@imrannayer would this be ok?

**Comment by edubxb** [comment]
Awesome, thanks for this contribution @ivankennethwang. We also need it!

**Comment by imrannayer** [comment]
> Welcome. Let me know if there is anything else I can do. Happy to help!

@ivankennethwang Can you look at my comment and add appropriate output.

**Comment by ivankennethwang** [comment]
> > Welcome. Let me know if there is anything else I can do. Happy to help!
> 
> @ivankennethwang Can you look at my comment and add appropriate output.

Thanks @imrannayer. Where can I see your comments? I don't see them [here](https://github.com/terraform-google-modules/terraform-google-memorystore/pull/206/files).

**Comment by imrannayer** [comment]
@ivankennethwang 

https://github.com/terraform-google-modules/terraform-google-memorystore/pull/206/files/2960c746088c47e9df09374f6d95b1fbf2c699c1

**Comment by ivankennethwang** [comment]
@imrannayer i sincerely apologize but i really don't see any github comments. :(

**Comment by imrannayer** [comment]
@ivankennethwang just scroll up on this screen and you will see code change request.

**Comment by ivankennethwang** [comment]
@imrannayer  sorry this is what i see, i really dont see any code change requests, or any other comment in the files changed tab.

image
image
image

**Comment by imrannayer** [comment]
@ivankennethwang I am not sure whayt interface you are using but here is whats neede. 

**@ivankennethwang you need to add node_type in output [here](https://github.com/terraform-google-modules/terraform-google-memorystore/blob/master/examples/redis-cluster/outputs.tf). Add following lines

```
output "node_type" {
  description = "The redis cluster node type"
  value       = module.redis_cluster.redis_cluster.node_type
}
```**

**Comment by ivankennethwang** [comment]
> @ivankennethwang I am not sure whayt interface you are using but here is whats neede.
> 
> **@ivankennethwang you need to add node_type in output [here](https://github.com/terraform-google-modules/terraform-google-memorystore/blob/master/examples/redis-cluster/outputs.tf). Add following lines
> 
> ```
> output "node_type" {
>   description = "The redis cluster node type"
>   value       = module.redis_cluster.redis_cluster.node_type
> }
> ```**
> ```

I'm just using github.com in Chrome browser. 😅 

Btw, updated and thanks! 🙇‍♂️

**Comment by ivankennethwang** [comment]
> @ivankennethwang lint test is failing. Can you plz execute
> 
> ```
> make docker_generate_docs
> ```

done, thank!

**Comment by imrannayer** [comment]
@ivankennethwang default value should be `null`. Provider automatically picks default value as `REDIS_HIGHMEM_MEDIUM`

**Comment by ivankennethwang** [comment]
> * @ivankennethwang default value should be `null`. Provider automatically picks default value as `REDIS_HIGHMEM_MEDIUM`.
> * Can u also update [version.tf](https://github.com/terraform-google-modules/terraform-google-memorystore/blob/master/modules/redis-cluster/versions.tf) for redis_cluster sub-module. Set min provider version to `5.24` as it was part of [5.24 release](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#5240-apr-8-2024).
> * Add an upgrade to v9 doc in [docs folder](https://github.com/terraform-google-modules/terraform-google-memorystore/tree/master/docs) mentioning that this will be a breaking change due to change in min provider version. [Here is an example](https://github.com/terraform-google-modules/terraform-google-memorystore/blob/master/docs/upgrading_to_v8.0.md)

Sorry, this is my first time contributing ever in a mature repository.

May I know when do we update the `README.md`, `CHANGELOG.md` and `versions.tf` at root level? I suppose those should be changed to include 5.24 and v9.0 also?

**Comment by imrannayer** [comment]
@ivankennethwang you are missing default = null


```
variable "node_type" {
  description = "The nodeType for the Redis cluster. If not provided, REDIS_HIGHMEM_MEDIUM will be used as default Possible values are: REDIS_SHARED_CORE_NANO, REDIS_HIGHMEM_MEDIUM, REDIS_HIGHMEM_XLARGE, REDIS_STANDARD_SMALL."
  type        = string
  default     = null
}

**Comment by ivankennethwang** [comment]
> @ivankennethwang you are missing default = null
> 
> ```
> variable "node_type" {
>   description = "The nodeType for the Redis cluster. If not provided, REDIS_HIGHMEM_MEDIUM will be used as default Possible values are: REDIS_SHARED_CORE_NANO, REDIS_HIGHMEM_MEDIUM, REDIS_HIGHMEM_XLARGE, REDIS_STANDARD_SMALL."
>   type        = string
>   default     = null
> }
> ```

updated, sorry about that.

**Comment by ivankennethwang** [comment]
how come for `authorization_mode` we set `default     = "AUTH_MODE_DISABLED"` though?

i thought node_type is quite similar to this[1], should we set it to null too?

[1] https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_cluster#authorization_mode

**Comment by imrannayer** [comment]
@ivankennethwang lint failed on document generation check

**Comment by imrannayer** [comment]
> how come for `authorization_mode` we set `default = "AUTH_MODE_DISABLED"` though?
> 
> i thought node_type is quite similar to this[1], should we set it to null too?
> 
> [1] https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_cluster#authorization_mode

Could have been set to null.

**Comment by ivankennethwang** [comment]
> > how come for `authorization_mode` we set `default = "AUTH_MODE_DISABLED"` though?
> > i thought node_type is quite similar to this[1], should we set it to null too?
> > [1] https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_cluster#authorization_mode
> 
> Could have been set to null.

Perhaps we can put it in a different pull request.

> @ivankennethwang lint failed on document generation check

Updated, thanks!

**Review by imrannayer — APPROVED** [review]

**Pull request merged**
