### PR TITLE
Fix: Ignore maintenance_schedule plan changes

### PR DESCRIPTION
**Pull request by addp009**
When there is an upcoming maintenance event is scheduled for MemoryStore Redis instance, Terraform tries to unset the `maintenance_schedule` read only attributes, resulting in a fail apply. 

This patch adds a lifecycle meta-argument to ignore changes in the maintenance_schedule block. 

image

### CODE REVIEW

**Comment by rafaelromcar** [comment]
We are experiencing the same problem. The fix proposed by @addp009 is the same that is proposed in the issue [#11871](https://github.com/hashicorp/terraform-provider-google/issues/11871) of the Terraform Google Provider. Please merge it as soon as possible. Thanks.

**Comment by gtsorbo** [comment]
Hi @addp009! Thanks for the contribution. Follow these instructions in order to contribute to Google-owned repos, and then we can move this PR along:

> Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> View this [failed invocation](https://github.com/terraform-google-modules/terraform-google-memorystore/pull/152/checks?check_run_id=14697628518) of the CLA check for more information.
> 
> For the most up to date status, view the checks section at the bottom of the pull request.

**Review by g-awmalik — APPROVED** [review]

**Pull request merged**
