### PR TITLE
add missing input: connect_mode

### LINKED ISSUE #17: missing input: connect_mode
https://www.terraform.io/docs/providers/google/r/redis_instance.html
This resource uses connect_mode but it is not available in this module and therefore should be added.

### PR DESCRIPTION
**Pull request by Santos92**
Fixes #17

### CODE REVIEW

**Comment by morgante** [comment]
Looks like it's only available in newer provider versions. Could you add a provider version constraint in the `versions.tf` file?

**Comment by Santos92** [comment]
Hey @morgante is there anything that is required of me or is this ready to be merged ? thank you for the help!

**Comment by sclausson** [comment]
@morgante thanks for merging this. Is it possible to release a new version of the module to include this change?

**Comment by morgante** [comment]
@sclausson Done!

**Pull request merged**
