### PR TITLE
added redis_auth

### PR DESCRIPTION
**Pull request by jmymy**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by morgante** [comment]
Test failure:
```
Profile: minimal
Version: (not specified)
Target:  local://

  ✔  redis-instance: Command: `gcloud redis instances describe test-redis --project=ci-memory-store-0e1c --region=us-east1 --format=json`
     ✔  Command: `gcloud redis instances describe test-redis --project=ci-memory-store-0e1c --region=us-east1 --format=json` should include {:memorySizeGb => 1}
     ✔  Command: `gcloud redis instances describe test-redis --project=ci-memory-store-0e1c --region=us-east1 --format=json` exit_status should eq 0
     ✔  Command: `gcloud redis instances describe test-redis --project=ci-memory-store-0e1c --region=us-east1 --format=json` stderr should eq ""

  Outputs
     ×  should reflect inputted variables
     
     expected: "us-east1-b"
          got: "us-east1-d"
     
     (compared using ==)

     ✔  should have a valid host ip
     ✔  should have a valid id
```

**Comment by jmymy** [comment]
thanks @morgante . Trying to debug this. `us-east1-b` was provided and so I'm unsure why it was created in `us-east1-d`.  Its running in HA so I'm wondering if multiple values were returned for `location_id`

**Comment by morgante** [comment]
Note you can also test locally to verify: https://github.com/terraform-google-modules/terraform-google-memorystore/blob/master/CONTRIBUTING.md#integration-testing

This codelab might help: https://codelabs.developers.google.com/codelabs/cft-onboarding#0

**Comment by jmymy** [comment]
haha thanks. My local env is all fubar'd at the moment (M1 mac) so was hoping this was an easy fix. sigh.

**Comment by jmymy** [comment]
found the issue. 
```
current_location_id - The current zone where the Redis endpoint is placed. 
For Basic Tier instances, this will always be the same as the [locationId] provided by 
the user at creation time. For Standard Tier instances, this can be either 
[locationId] or [alternativeLocationId] and can change after a failover event.
```

**Comment by jmymy** [comment]
@morgante any update to why the test failed? 

converged and verified on my env:
```
Profile: memcache
Version: (not specified)
Target:  local://

  ✔  memcache-instance: Command: `gcloud beta memcache instances describe example-memcache --project=ci-memory-store-fdcb --region=us-east1 --format=json`
     ✔  Command: `gcloud beta memcache instances describe example-memcache --project=ci-memory-store-fdcb --region=us-east1 --format=json` nodeConfig.cpucount matches var.cpu_count
     ✔  Command: `gcloud beta memcache instances describe example-memcache --project=ci-memory-store-fdcb --region=us-east1 --format=json` nodeConfig.memorySizeMb matches var.memory_size_mb
     ✔  Command: `gcloud beta memcache instances describe example-memcache --project=ci-memory-store-fdcb --region=us-east1 --format=json` exit_status should eq 0
     ✔  Command: `gcloud beta memcache instances describe example-memcache --project=ci-memory-store-fdcb --region=us-east1 --format=json` stderr should eq ""

  Outputs
     ✔  should reflect inputted variables
     ✔  should have a valid id

Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 6 successful, 0 failures, 0 skipped
```

```
Profile: minimal
Version: (not specified)
Target:  local://

  ✔  redis-instance: Command: `gcloud redis instances describe test-minimal --project=ci-memory-store-fdcb --region=us-east1 --format=json`
     ✔  Command: `gcloud redis instances describe test-minimal --project=ci-memory-store-fdcb --region=us-east1 --format=json` should include {:memorySizeGb => 1}
     ✔  Command: `gcloud redis instances describe test-minimal --project=ci-memory-store-fdcb --region=us-east1 --format=json` exit_status should eq 0
     ✔  Command: `gcloud redis instances describe test-minimal --project=ci-memory-store-fdcb --region=us-east1 --format=json` stderr should eq ""

  Outputs
     ✔  should reflect inputted variables
     ✔  should have a valid host ip
     ✔  should have a valid id

Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 6 successful, 0 failures, 0 skipped
```

```
Profile: redis
Version: (not specified)
Target:  local://

  ✔  redis-instance: Command: `gcloud redis instances describe test-redis --project=ci-memory-store-fdcb --region=us-east1 --format=json`
     ✔  Command: `gcloud redis instances describe test-redis --project=ci-memory-store-fdcb --region=us-east1 --format=json` memorySizeGb matches var.memory_size_gb
     ✔  Command: `gcloud redis instances describe test-redis --project=ci-memory-store-fdcb --region=us-east1 --format=json` authEnabled matches var.auth_enabled
     ✔  Command: `gcloud redis instances describe test-redis --project=ci-memory-store-fdcb --region=us-east1 --format=json` exit_status should eq 0
     ✔  Command: `gcloud redis instances describe test-redis --project=ci-memory-store-fdcb --region=us-east1 --format=json` stderr should eq ""

  Outputs
     ✔  should reflect inputted variables
     ✔  should have a valid host ip
     ✔  should have a valid id

Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 7 successful, 0 failures, 0 skipped
```

**Comment by bharathkkb** [comment]
@jmymy looks like it may have been flaky re running now

**Comment by jmymy** [comment]
@bharathkkb @morgante any insight into the failure?

**Comment by bharathkkb** [comment]
@jmymy looks like it's failing at the destroy phase with 
```
module.memstore.google_redis_instance.default: Still destroying... [id=projects/PROJECT_ID/locations/us-east1/instances/test-minimal, 1m30s elapsed]
       module.memstore.google_redis_instance.default: Still destroying... [id=projects/PROJECT_ID/locations/us-east1/instances/test-minimal, 1m40s elapsed]
       module.memstore.google_redis_instance.default: Still destroying... [id=projects/PROJECT_ID/locations/us-east1/instances/test-minimal, 1m50s elapsed]
       module.memstore.google_redis_instance.default: Destruction complete after 1m57s
       module.memstore.module.enable_apis.google_project_service.project_services["redis.googleapis.com"]: Destroying... [id=PROJECT_ID/redis.googleapis.com]
       module.memstore.module.enable_apis.google_project_service.project_services["redis.googleapis.com"]: Still destroying... [id=PROJECT_ID/redis.googleapis.com, 10s elapsed]
       module.memstore.module.enable_apis.google_project_service.project_services["redis.googleapis.com"]: Still destroying... [id=PROJECT_ID/redis.googleapis.com, 20s elapsed]
       
       Error: Error when reading or editing Project Service PROJECT_ID/redis.googleapis.com: Error disabling service "redis.googleapis.com" for project "PROJECT_ID": Error waiting for api to disable: Error code 9, message: [Hook call/poll resulted in failed op for service 'redis.googleapis.com': Not ready to deactivate the service on this project; ensure there are no more resources managed by this service.] with failed services [redis.googleapis.com]
```
 It does seem to be destroying in the correct order, so we may have to set `disable_services_on_destroy` as a work around here https://github.com/terraform-google-modules/terraform-google-memorystore/blob/b516843c4fe6f2cad938b1c28f3520cce28a9213/main.tf#L40

**Comment by jmymy** [comment]
in just the test-minimal?

**Comment by jmymy** [comment]
That var doesn't exist in this repo. Do I need to add it? otherwise, it disables the enabling of the apis which I wouldn't think we'd want to disable in the tests.  @bharathkkb

**Comment by morgante** [comment]
@jmymy In the module invocation [here](https://github.com/terraform-google-modules/terraform-google-memorystore/blob/master/main.tf#L40), we should be fine to add it:

```
module "enable_apis" {
  source  = "terraform-google-modules/project-factory/google//modules/project_services"
  version = "9.2.0"

  project_id  = var.project
  enable_apis = var.enable_apis
  disable_services_on_destroy = false

  activate_apis = [
    "redis.googleapis.com",
  ]
}
```

**Comment by mirobertod** [comment]
Any update on this PR?

Thanks

**Review by morgante — APPROVED** [review]

**Comment by caddac** [comment]
not sure where the bug actually lies, but on provider `3.60.0` I get error `Computed attributes cannot be set, but a value was set for "auth_string".`

**Comment by jmymy** [comment]
> not sure where the bug actually lies, but on provider `3.60.0` I get error `Computed attributes cannot be set, but a value was set for "auth_string".` I have not specified `auth_enabled`.

https://github.com/hashicorp/terraform-provider-google/issues/8400

looks like they changed some behavior upstream

**Comment by morgante** [comment]
@jmymy It looks like we need to remove auth_string as a configurable input.

**Comment by jmymy** [comment]
> @jmymy It looks like we need to remove auth_string as a configurable input.

ill do up the PR this afternoon

**Pull request merged**
