### PR TITLE
Initial update of CI testing setup

### PR DESCRIPTION
**Pull request by milesmatthias**
Fixes https://github.com/terraform-google-modules/terraform-google-memorystore/issues/12

### CODE REVIEW

**Comment by morgante** [comment]
@milesmatthias Looks like a duplicate of #13?

**Comment by milesmatthias** [comment]
@morgante yes, I didn't see #13 before submitting this work, but it looks like that is in draft form, whereas mine is ready to merge.

**Comment by morgante** [comment]
@milesmatthias Can you configure the Cloud Build checks for this before we merge?

**Comment by milesmatthias** [comment]
@morgante yup, adding those.

**Comment by morgante** [comment]
@milesmatthias Looks like this is being handled in #13, you can drop work on it for now.

**Comment by milesmatthias** [comment]
Thanks @morgante, will do.

**Pull request closed without merging**
