### PR TITLE
feat: add persistence configuration for Redis

### PR DESCRIPTION
**Pull request by Dariusch**
credits to: https://github.com/terraform-google-modules/terraform-google-memorystore/pull/108

I want to see this merged, that's why I picked it up, as the PR seems to be stale

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@Dariusch
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by sgrzemski** [comment]
Yes, yes yes! Much needed feature.

**Comment by comment-bot-dev** [comment]
@Dariusch
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@Dariusch
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by adriagalin — APPROVED** [review]

**Comment by sgrzemski** [comment]
@apeabody @bharathkkb is there a chance we can get that merged?

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @Dariusch!  It looks like `persistence_config` was added in TPG 4.38.0, can we please bump the minimum version to match: https://github.com/terraform-google-modules/terraform-google-memorystore/blob/ec37efc4fe1bac943f2ca42eab3cb2ec16a7331e/versions.tf#L23

**Comment by Dariusch** [comment]
> Thanks for the contribution @Dariusch! It looks like `persistence_config` was added in TPG 4.38.0, can we please bump the minimum version to match:
> 
> https://github.com/terraform-google-modules/terraform-google-memorystore/blob/ec37efc4fe1bac943f2ca42eab3cb2ec16a7331e/versions.tf#L23

I updated the minimum required version to 4.38.0.

**Comment by sgrzemski** [comment]
@apeabody @bharathkkb the requested changes were implemented. WDYT of releasing this change? I need it badly.

**Review by apeabody — APPROVED** [review]

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @Dariusch!  Running the CI after the rebase to make sure everything is still good.

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @Dariusch!

**Comment by sgrzemski** [comment]
Amazing, thanks @Dariusch @apeabody!
Can we have that released?

**Pull request merged**
