### PR TITLE
feat!: Updated CMEK attribute

### PR DESCRIPTION
**Pull request by ramneekkh**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@ramneekkh
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR @ramneekkh 
We will also need to bump the min provider version https://github.com/terraform-google-modules/terraform-google-memorystore/blob/master/versions.tf#L23 to 4.28 where this field was added https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4280-july-11-2022

**Comment by comment-bot-dev** [comment]
@ramneekkh
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]

**Comment by bharathkkb** [comment]
Hold for next breaking release

**Comment by comment-bot-dev** [comment]
@ramneekkh
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request merged**
