### PR TITLE
Feat:! Add Redis instance persistent configuration.

### PR DESCRIPTION
**Pull request by huy-axie**
Example:

```
 persistence_config      = {
      "persistence_mode" = "RDB",
      "rdb_snapshot_period" = "ONE_HOUR"
  }
```
Reference document: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_instance#persistence_config

- [x] terraform fmt.
- [x]  make generate_docs.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@huy-axie
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
examples/redis/main.tf
--- old/examples/redis/main.tf
+++ new/examples/redis/main.tf
@@ -28,9 +28,9 @@
   transit_encryption_mode = "SERVER_AUTHENTICATION"
   authorized_network      = module.test-vpc-module.network_id
   memory_size_gb          = 1
-  persistence_config      = {
-      "persistence_mode" = "RDB",
-      "rdb_snapshot_period" = "ONE_HOUR"
+  persistence_config = {
+    "persistence_mode"    = "RDB",
+    "rdb_snapshot_period" = "ONE_HOUR"
   }
 
 }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@huy-axie
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@huy-axie
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
main.tf
--- old/main.tf
+++ new/main.tf
@@ -39,8 +39,8 @@
   dynamic "persistence_config" {
     for_each = var.persistence_config != null ? [var.persistence_config] : []
     content {
-      persistence_mode        = persistence_config.value["persistence_mode"]
-      rdb_snapshot_period     = persistence_config.value["rdb_snapshot_period"]
+      persistence_mode    = persistence_config.value["persistence_mode"]
+      rdb_snapshot_period = persistence_config.value["rdb_snapshot_period"]
     }
   }
 
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Review by bharathkkb — COMMENTED** [review]
Thanks for the PR. Could you fix the formatting and sign the CLA?

**Comment by grzegdl** [comment]
Hi, can I help somehow to push it further?

**Pull request closed without merging**
